{
  "unversionedId": "writing_tests/failing_with_a_custom_message",
  "id": "writing_tests/failing_with_a_custom_message",
  "title": "Failing with a custom message",
  "description": "Sometimes your validation logic might result in different failure reasons that are unknown before you run the test. In this case the message argument is not as useful, and instead you should omit it. Vest allows you to provide the message within the test body itself by doing one of the following:",
  "source": "@site/docs/writing_tests/failing_with_a_custom_message.md",
  "sourceDirName": "writing_tests",
  "slug": "/writing_tests/failing_with_a_custom_message",
  "permalink": "/docs/writing_tests/failing_with_a_custom_message",
  "editUrl": "https://github.com/ealush/vest-website/edit/main/docs/writing_tests/failing_with_a_custom_message.md",
  "tags": [],
  "version": "current",
  "sidebarPosition": 3,
  "frontMatter": {
    "sidebar_position": 3
  },
  "sidebar": "tutorialSidebar",
  "previous": {
    "title": "Writing Asynchronous Tests",
    "permalink": "/docs/writing_tests/async_tests"
  },
  "next": {
    "title": "Warn-only tests",
    "permalink": "/docs/writing_tests/warn_only_tests"
  }
}